import { createHash } from "node:crypto";
import { ObjectNotFoundError, isOwnedProjectObjectPath } from "./objectStorage.ts";
import { encodeTrackMidi } from "./track-midi.ts";

/**
 * Track MIDI pointers intentionally live beside the workspace snapshot. This
 * avoids a schema migration while keeping the generated bytes out of JSONB.
 */
export const PROJECT_MIDI_METADATA_KEY = "midiFiles";
export const PROJECT_MIDI_CONTENT_TYPE = "audio/midi";

export type ProjectMidiFileMetadata = {
  objectPath: string;
  sha256: string;
};

export type ProjectMidiMetadata = Record<string, ProjectMidiFileMetadata>;

export type ProjectMidiDocument = Record<string, unknown>;

export type ProjectMidiStorage = {
  trackMidiObjectPath(ownerId: string, projectId: string): string;
  upload(objectPath: string, bytes: Buffer, contentType: string): Promise<void>;
  getFile(objectPath: string): Promise<unknown>;
};

export class ProjectMidiValidationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "ProjectMidiValidationError";
  }
}

function record(value: unknown): Record<string, unknown> | null {
  return value && typeof value === "object" && !Array.isArray(value)
    ? value as Record<string, unknown>
    : null;
}

function validHash(value: unknown): value is string {
  return typeof value === "string" && /^[0-9a-f]{64}$/.test(value);
}

function setMetadata(
  metadata: ProjectMidiMetadata,
  trackId: string,
  value: ProjectMidiFileMetadata,
): void {
  Object.defineProperty(metadata, trackId, {
    configurable: true,
    enumerable: true,
    value,
    writable: true,
  });
}

/**
 * Invalid/stale metadata is ignored rather than trusted. The next save then
 * writes a fresh object and replaces it with metadata generated on the server.
 */
export function readProjectMidiMetadata(document: ProjectMidiDocument | null | undefined): ProjectMidiMetadata {
  const raw = record(document?.[PROJECT_MIDI_METADATA_KEY]);
  if (!raw) return {};
  const metadata: ProjectMidiMetadata = {};
  for (const [trackId, value] of Object.entries(raw)) {
    const entry = record(value);
    if (!entry || typeof entry.objectPath !== "string" || !validHash(entry.sha256)) continue;
    setMetadata(metadata, trackId, {
      objectPath: entry.objectPath,
      sha256: entry.sha256,
    });
  }
  return metadata;
}

export function withProjectMidiMetadata(
  document: ProjectMidiDocument,
  metadata: ProjectMidiMetadata,
): ProjectMidiDocument {
  return {
    ...document,
    [PROJECT_MIDI_METADATA_KEY]: metadata,
  };
}

function midiScore(document: ProjectMidiDocument): {
  tempo: number;
  tracks: Array<{
    id: string;
    name?: string;
    instrument?: string;
    midiProgram?: number;
    regions: Array<{
      startBeat: number;
      notes: Array<{
        pitch: number;
        velocity: number;
        startBeat: number;
        durationBeats: number;
      }>;
    }>;
  }>;
} {
  const score = record(document.score);
  if (!score || !Array.isArray(score.tracks)) {
    throw new ProjectMidiValidationError("Workspace document score must contain a tracks array");
  }
  const seen = new Set<string>();
  const tracks = score.tracks.map((value) => {
    const track = record(value);
    if (!track || typeof track.id !== "string" || !track.id || seen.has(track.id)) {
      throw new ProjectMidiValidationError("Workspace document score contains an invalid or duplicate track id");
    }
    if (!Array.isArray(track.regions)) {
      throw new ProjectMidiValidationError(`Track ${track.id} must contain a regions array`);
    }
    seen.add(track.id);
    return {
      id: track.id,
      ...(typeof track.name === "string" ? { name: track.name } : {}),
      ...(typeof track.instrument === "string" ? { instrument: track.instrument } : {}),
      ...(typeof track.midiProgram === "number" ? { midiProgram: track.midiProgram } : {}),
      regions: track.regions as Array<{
        startBeat: number;
        notes: Array<{
          pitch: number;
          velocity: number;
          startBeat: number;
          durationBeats: number;
        }>;
      }>,
    };
  });
  return {
    tempo: typeof score.tempo === "number" ? score.tempo : 120,
    tracks,
  };
}

function objectHash(bytes: Buffer): string {
  return createHash("sha256").update(bytes).digest("hex");
}

async function writeTrack(
  storage: ProjectMidiStorage,
  ownerId: string,
  projectId: string,
  bytes: Buffer,
): Promise<string> {
  const objectPath = storage.trackMidiObjectPath(ownerId, projectId);
  await storage.upload(objectPath, bytes, PROJECT_MIDI_CONTENT_TYPE);
  return objectPath;
}

/**
 * Materializes every current score track, including empty tracks, as an
 * independent SMF. A previous file is reused only when its hash and owner /
 * project-scoped object path both match and the object still exists.
 */
export async function persistProjectMidiFiles(input: {
  document: ProjectMidiDocument;
  previousDocument?: ProjectMidiDocument | null;
  ownerId: string;
  projectId: string;
  storage: ProjectMidiStorage;
}): Promise<ProjectMidiMetadata> {
  const score = midiScore(input.document);
  const previous = readProjectMidiMetadata(input.previousDocument);
  const metadata: ProjectMidiMetadata = {};

  for (const track of score.tracks) {
    const bytes = encodeTrackMidi(score, track);
    const sha256 = objectHash(bytes);
    const previousFile = previous[track.id];
    if (
      previousFile
      && previousFile.sha256 === sha256
      && isOwnedProjectObjectPath(previousFile.objectPath, input.ownerId, input.projectId)
    ) {
      try {
        await input.storage.getFile(previousFile.objectPath);
        setMetadata(metadata, track.id, previousFile);
        continue;
      } catch (error) {
        if (!(error instanceof ObjectNotFoundError)) throw error;
      }
    }

    setMetadata(metadata, track.id, {
      objectPath: await writeTrack(input.storage, input.ownerId, input.projectId, bytes),
      sha256,
    });
  }

  return metadata;
}